pruebas_index:
    path: /pruebas/{lang}/{name}/{page}
    defaults: {_controller: AppBundle:Pruebas:Index, lang: es, name: pepito, page:1}
    methods: [GET]
    requirements:
      lang: es|ca|en
      name: \w+
      page: \d+
